version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    restart: always
    container_name: mongodb
    ports:
      - ${MONGO_PORTS}:${MONGO_PORTS}
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}


  app:
    build: .
    container_name: shortify_app
    depends_on:
      - mongodb
    ports:
      - ${WEB_PORTS}:${WEB_PORTS}
    environment:
      MONGO_URI: ${MONGO_URI}

volumes:
  mongo-data:
